# Copyright 2020 The TensorFlow Probability Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# ============================================================================
name: Tests
on: [push, pull_request]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        shard: [0]
    env:
      SHARD: ${{ matrix.shard }}
      NUM_SHARDS: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Tests
        run: |
          ./testing/run_github_tests.sh
      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v1
        with:
            name: testlogs-${{ matrix.shard }}
            path: bazel-testlogs
  
  tests2:
    name: Tests_arm64
    runs-on: ubuntu-latest_arm64
    strategy:
      matrix:
        pyver: [cp37-cp37m]
        shard: [0]
        arch: ['aarch64']
    env:
      py: /opt/python/${{ matrix.pyver }}/bin/python
      img: quay.io/pypa/manylinux2014_${{ matrix.arch }}
      SHARD: ${{ matrix.shard }}
      NUM_SHARDS: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} \
          bash -exc '${{ env.py }} -m pip install virtualenv && ${{ env.py }} -m venv .env && \
          source .env/bin/activate && \
          ./testing/run_github_tests.sh&& \
          deactivate'
          
      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v1
        with:
            name: testlogs-${{ matrix.shard }}
            path: bazel-testlogs
